name: New Pull request Open
"on":
  pull_request:
    branches:
      - master

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            PR is now waiting for a maintainer to run the acceptance tests.

            **Note for the maintainer:** To run the acceptance tests, please comment */run-example-tests* on the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
